### ISSUE TITLE
Draft releases

### ISSUE THREAD

**Issue by Cimbali** [fnkr/github-action-ghr#3]
This action creates a release for a given tag, when it doesn’t exist. Would it possible to (have an option to) mark this release as a draft release, i.e. not public?

This is the result of what happens when clicking “Save draft” instead of “Publish Release” when editing a release manually. Other CI providers also provide this option, e.g. [appveyor](https://www.appveyor.com/docs/deployment/github/#provider-settings)

**Comment by fnkr** [comment]
Should be easy to implement as ghr already supports this using the `-draft` flag. I will take a look at this tomorrow.

**Comment by fnkr** [comment]
Hi,

[ghr](https://github.com/tcnksm/ghr) provides such an option and I created [a branch](https://github.com/fnkr/github-action-ghr/tree/ghr-options) to test this, unfortunately while testing I discovered that draft releases can't reference existing tags. Since this action is triggered only after a tag is created I see no way how this can be done.

**Comment by Cimbali** [comment]
So draft releases can only create new tags, not reference existing ones? That’s too bad.

**Comment by fnkr** [comment]
Hi @Cimbali,

it used to be like this. Apparently GitHub recently made a change here and this is now working. Can you please test if it is working for you as well (`ghr-options` branch)?

```yaml
on: push
name: Release
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: mkdir bin && touch bin/test
      - name: Release
        uses: fnkr/github-action-ghr@ghr-options
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: xz
          GHR_PATH: bin/
          GHR_DRAFT: yes
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
