### ISSUE TITLE
[ERR] refs/heads/master is not a tag, exiting...

### ISSUE THREAD

**Issue by maximousblk** [fnkr/github-action-ghr#8]
workflow:

```yml
name: test

on:
  watch:
    types: [started] # does this have something to do with it?

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'refs/tags/1.0' # Explicitly referencing a tag

    - name: tasks
      run: |
          echo ${{ github.ref }} > ref.txt
          cat ref.txt # outputs "refs/heads/master"

    - name: Release
      uses: fnkr/github-action-ghr@v1
#       if: startsWith(github.ref, 'refs/tags/') # if I uncomment this the step is skipped
      env:
        GHR_COMPRESS: zip
        GHR_PATH: ref.txt
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

@fnkr Please help. I'm new to github actions and don't know how checkout action works.

It is a private repo which I edit only using the Github's online editor. Do I have to create tags locally and then push?

**Comment by fnkr** [comment]
> Do I have to create tags locally and then push?

That's one way to do it but you can also create a new release on GitHub, which will also create a tag and trigger the workflow: https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release

You'll need to update your workflow. You can use the usage example from the README. Afterwards just create a new release like described in the support document.

```yaml
on: push
name: Build and release on push
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: tasks
        run: |
          echo ${{ github.ref }} > ref.txt
          cat ref.txt
      - name: Release
        uses: fnkr/github-action-ghr@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: ref.txt
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Please don't override the ref for the checkout action. You want to build the commit you just pushed or tagged not some predefined tag.
